### ISSUE TITLE
Error for savepath

### ISSUE THREAD

**Issue by davewest2** [shanerodrigues/compose-uvc-camera#1]
Hi,

Thanks for the repo it's potentially really useful. I am having an issue with the savepath, getting the following error on the log. Apologies if this is a trivial fix (I'm new to this!) but could you advise how to change the path. I don't need to store the photo outside of the app so using the app's own internal storage is fine. Thanks for any help you can offer.

023-04-13 10:41:50.044 29031-31647 RenderManager           com.example.camerauvctest            E  Failed to write file, err = /storage/emulated/0/DCIM/Camera/IMG_JJCamera_20230413104150039.jpg: open failed: ENOENT (No such file or directory)
                                                                                                    java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/IMG_JJCamera_20230413104150039.jpg: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:492)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
                                                                                                    	at com.jiangdg.ausbc.render.RenderManager.saveImageInternal(RenderManager.kt:421)
                                                                                                    	at com.jiangdg.ausbc.render.RenderManager.handleMessage(RenderManager.kt:141)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.Linux.open(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8494)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:478)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:125) 
                                                                                                    	at com.jiangdg.ausbc.render.RenderManager.saveImageInternal(RenderManager.kt:421) 
                                                                                                    	at com.jiangdg.ausbc.render.RenderManager.handleMessage(RenderManager.kt:141) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
2023-04-13 10:41:50.045 29031-31647 RenderManager           com.example.camerauvctest            E  Failed to save file /storage/emulated/0/DCIM/Camera/IMG_JJCamera_20230413104150039.jpg

**Comment by ColtonIdle** [comment]
I was able to write to apps internal storage via

```
  cameraClient.captureImage(
      object : ICaptureCallBack {
          override fun onBegin() {
              TODO("Not yet implemented")
          }

          override fun onComplete(path: String?) {
              TODO("Not yet implemented")
          }

          override fun onError(error: String?) {
              TODO("Not yet implemented")
          }
      },
      path = context.filesDir.path.plus("/myimage.jpg"))
```

**Comment by davewest2** [comment]
Thanks ColtonIdle! Image saved and accessible, great stuff. I have now found, however, that the captureImage function seems to fire automatically when the app starts up. The capture image button does not appear to trigger the captureImage function so the image captured on start up is never overwritten. I don't actually need this function so it's usable as is, but it would be useful to understand why this is happening and to correct it, perhaps for future purposes.

**Comment by ColtonIdle** [comment]
weird. i didn't see that problem. im away on holiday right now, but i would just comment out that function and make sure that it indeed isn't triggered and more and then trace through the code to make sure that callback is only called on button press. let me know after you try that and i can try to debug, but it might just be something simple.

**Comment by shanerodrigues** [comment]
hey @davewest2 sorry for getting back to you so late, I'm glad to hear that Colton was able to help you out. Are you still facing the captureImage issue?

**Comment by davewest2** [comment]
Hi Shane. Hey, no worries! And yes, I'm still unable to get the captureImage function linked to the onClickListener. I've enlisted some more experienced help in trying to explain the behaviour but without fruit at the moment.
________________________________

**Comment by shanerodrigues** [comment]
I'd suggest trying to mimic the structure that's implemented in this demo. I believe the button only worked when it was within that function with the cameraPreview or otherwise, the onClick wouldn't fire.

**Comment by ColtonIdle** [comment]
@davewest2 I forgot about this actually, but if you can post some code maybe we can take a look. Without that its shooting in the dark

**Comment by davewest2** [comment]
Absolutely. I don't think the world is ready for my code, but here goes! I've taken the code in the repo and made the following changes in addition to the path as suggested by Shane. I'm using the Coil library to asynchronously get the image from the captureImage function and place it on the screen (I haven't concerned myself with positioning at the moment as ultimately I don't want to see anything in the app):

Change to the myApp composable:
```
@Composable
fun MyApp(){
    val context = LocalContext.current
    Box(modifier = Modifier
        .fillMaxWidth(0.5f)
    ) {
        UVCCameraPreview(rememberCameraClient(context))
    }
    Box(modifier = Modifier.fillMaxWidth(0.5f)) {
        DisplayImage()
    }
}
```

And added this composable to retrieve and display the image from the captureImage function.

```
@Composable
fun DisplayImage() {
    Column(
        Modifier
            .fillMaxSize()
            .fillMaxHeight()
            .fillMaxWidth(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {

        val file = File(LocalContext.current.filesDir, "myimage.jpg")
        val contents = file.absolutePath
        val imgFile = File(contents)
        var imgBitmap: Bitmap? = null
        if (imgFile.exists()) {
            imgBitmap = BitmapFactory.decodeFile(imgFile.absolutePath)
        }

        AsyncImage(
            model = ImageRequest.Builder(LocalContext.current)
                .data(imgBitmap)
                .build(),
            placeholder = painterResource(id = R.drawable.library_image),
            contentDescription = "Image",
            modifier = Modifier
                .fillMaxWidth()
                .height(200.dp)
                .padding(10.dp)
        )
    }
}
```

**Comment by ColtonIdle** [comment]
@davewest2 what's the current error/exception that you're getting? I wonder if it has to do with your target sdk level in your build.gradle

I'm playing around in my app and noticed if I went from target 30 down to 29, then it crashes on the save function as well. not sure why.

**Comment by ColtonIdle** [comment]
@shanerodrigues can you confirm which android version you tested on? really dumbfounded why downgrading my target api level breaks this. lol

**Comment by shanerodrigues** [comment]
> @shanerodrigues can you confirm which android version you tested on? really dumbfounded why downgrading my target api level breaks this. lol

I've only tested it on Android 9 and in the demo, the targetSDK is set to 28. Unfortunately, I do not have access to an external USB camera, so I'm unable to test out the application myself.

**Comment by ColtonIdle** [comment]
Okay, seems like android 9 with 3.2.8 of the usblib work. but if you want android 12+ you need the 3.3.3 lib.

@shanerodrigues do you happen to know how i can get this to work without writing to disk? id love a callback of just a byte[]. not sure if that's something more appropriate to ask of the libusb maintainer.

**Comment by shanerodrigues** [comment]
@ColtonIdle Sorry, I don't really know the intricacies of the library itself. The library maintainer would definitely be able to assist you with that.

**Comment by ColtonIdle** [comment]
all good. cheers. this repo is a great starting off point w/ compose

**Comment by davewest2** [comment]
Apologies both, have been off cycling in Belgium! So I'll need to put in some more debug tags to more easily see the sequence of events but there are warnings and information lines regarding the save path but no error as such that I can discern. I've uploaded an Excel file of the logcat - first mention of the UVCCameraTest package is at 14:56:59.747 (line 331) with captureImage at 14.57.18.154 and onBegin called at 14:57:18:206. Apologies for the formatting - I need to work on exporting logcat data!
[logcat UVCCameraTest .xlsx](https://github.com/shanerodrigues/compose-uvc-camera/files/11443559/logcat.UVCCameraTest.xlsx)
